# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~> 3.2.2"
gem "middleman-livereload", :git => "git://github.com/middleman/middleman-livereload.git"
gem 'middleman-autoprefixer'
gem "rack-legacy"
# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]
